name: Keep Bot Awake

on:
  schedule:
    # Runs every minute
    - cron: '*/1 * * * *'

jobs:
  ping-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the bot endpoint
        run: |
          curl -m 10 --retry 2 --retry-delay 5 https://telegram-vent-bot-j14c.onrender.com/ping || echo "Bot ping failed"
#hey
